PACKAGE EDU.KPI; 
 
IMPORT JAVA.LANG.ANNOTATION.ELEMENTTYPE; 
IMPORT JAVA.LANG.ANNOTATION.RETENTION; 
IMPORT JAVA.LANG.ANNOTATION.RETENTIONPOLICY; 
IMPORT JAVA.LANG.ANNOTATION.TARGET; 
 
@RETENTION(RETENTIONPOLICY.RUNTIME) 
@TARGET(ELEMENTTYPE.METHOD) 
PUBLIC @INTERFACE CALLTHIS { 

} 
