PACKAGE EDU.KPI; 
 
IMPORT JAVA.IO.PRINTSTREAM; 
 
PUBLIC INTERFACE RATIONALEXPRESSION { 
    VOID PRINT(PRINTSTREAM OUT); 
 
    POLYNOMIAL GETNUMERATOR(); 
    VOID SETNUMERATOR(POLYNOMIAL NUMERATOR); 
 
    POLYNOMIAL GETDENOMINATOR(); 
    VOID SETDENOMINATOR(POLYNOMIAL DENOMINATOR); 
 
} 
