PACKAGE EDU.KPI; 
 
IMPORT JAVA.IO.PRINTSTREAM; 
 
PUBLIC CLASS REALRATIONALEXPRESSION EXTENDS POLYNOMIAL IMPLEMENTS RATIONALEXPRESSION { 
    PRIVATE POLYNOMIAL DENOMINATOR; 
 
    PUBLIC REALRATIONALEXPRESSION(POLYNOMIAL NUMERATOR, POLYNOMIAL DENOMINATOR) { 
        SUPER(NUMERATOR.SYMBOL, NUMERATOR.COEFFICIENTS); 
        THIS.DENOMINATOR = DENOMINATOR; 
    } 
 
    @OVERRIDE 
    PUBLIC VOID PRINT(PRINTSTREAM OUT) { 
        OUT.PRINTLN(TOSTRING()); 
    } 
 
    @OVERRIDE 
    PUBLIC POLYNOMIAL GETNUMERATOR() { 
        RETURN new POLYNOMIAL(SYMBOL, COEFFICIENTS); 
    } 
 
    @OVERRIDE 
    PUBLIC VOID SETNUMERATOR(POLYNOMIAL NUMERATOR) { 
        THIS.COEFFICIENTS = NUMERATOR.COEFFICIENTS; 
        THIS.SYMBOL = NUMERATOR.SYMBOL; 
    } 
 
    @OVERRIDE 
    PUBLIC POLYNOMIAL GETDENOMINATOR() { 
        RETURN DENOMINATOR; 
    } 
 
    @OVERRIDE 
    PUBLIC VOID SETDENOMINATOR(POLYNOMIAL DENOMINATOR) { 
        THIS.DENOMINATOR = DENOMINATOR; 
    } 
 
    @OVERRIDE 
    PUBLIC STRING TOSTRING() { 
        FINAL var sb = new STRINGBUILDER(SUPER.TOSTRING()); 
        SB.APPEND('\N'); 
 
        var DENOMINATORSTR = DENOMINATOR.TOSTRING(); 
        SB.APPEND("–".REPEAT(DENOMINATORSTR.LENGTH())); 
        SB.APPEND('\N'); 
 
        SB.APPEND(DENOMINATORSTR); 
 
        RETURN SB.TOSTRING(); 
    } 
} 
